spring:
  application:
    name: microservice-apiprice

  data:
    mongodb:

      uri: mongodb://localhost:27017,localhost:27017
      database: shop
     
camel:
  springboot:
    name: PriceEvent

server:
  port: 0

# kafka
kafka:
  bootstrap-server: localhost:29092
  acks: all
  retries: 2147483647
  batch-size: 131072
  buffer-memory: 80000000
  client-id: PriceEvent
  idempotence: true
  compression-type: lz4
  topic-name: price-v1
  user: producer-user
  password: producer-pwd

schedule-time: 300

